### ISSUE TITLE
Tags Can Be Duplicate

### ISSUE THREAD

**Issue by tubbo** [workarea-commerce/workarea#112]
**Describe the bug**
It's possible for tags on Workarea models to be duplicate, which causes incorrect tag counts in the UI.

**To Reproduce**
1. `Workarea::Catalog::Product.create!(name: 'foo', tags: %w(foo bar baz foo))`
2. `tag = Workarea::Catalog::Product.all_tags.find { |tag| tag[:name] = "foo" }`
3. `tag[:count] # => 2`

**Expected behavior**
Duplicate tags in the same model shouldn't count as multiple instances. `tag[:count]` in the previous example should be `1`.

**Workarea Setup (please complete the following information):**
 - Workarea Version: v3.4

**Additional context**
This was reported by an SI while working with the blog storefront.

**Comment by ebigler** [comment]
duplicate tags are now stripped on save
![QA_tags](https://user-images.githubusercontent.com/50744988/65801427-1acbc400-e147-11e9-8e0b-c99086e02d07.gif)
