### ISSUE TITLE
License Language - Legal

### ISSUE THREAD

**Issue by osseonews** [workarea-commerce/workarea#137]
We plan to use a hosting company to host Workarea. However, your license agreement (copied below), appears to suggest that a hosting company cannot actually host this software, as that would be a "Commerce Service" for the hosting company under your definition. This implies that the software is not really open source, as you can't have any company host it, other than your own. As most companies are not set up to manage hardware and software, how exactly is this supposed to work? We can only host the software on our own servers and are not permitted to use a hosting company to host it for us? Please clarify. Thanks.

Legal Language:
> You may make production use of the Licensed Work without an additional license agreement with WebLinc so long as you do not use the Licensed Work for a Commerce Service. A "Commerce Service" is a commercial offering that allows third parties (other than your employees and contractors) to access the functionality of the Licensed Work by creating or managing commerce functionality, the products, taxonomy, assets and/or content of which are controlled by such third parties.

**Comment by jhill** [comment]
Hi, thanks for reaching out. We'll try and clarify how we describe it, but you're totally fine to host it with a hosting company. 

If a hosting company wants to offer Workarea hosting as a service, we'd like to have a conversation before that happens.
