### ISSUE TITLE
Disabling a default category breaks admin screen

### ISSUE THREAD

**Issue by ryaan-anthony** [workarea-commerce/workarea#157]
Workarea 3.4.16

* Add default category to product
* Disable category
* View product in admin
* 500 error is raised when trying to compare default_category to another category to render the cards

> **undefined method `id' for #<Workarea::Admin::CategoryViewModel:0x000055992e4e1098>**
> workarea-admin-3.4.16/app/views/workarea/admin/catalog_products/_cards.html.haml at line 171

```
                - model.rules_categories.each do |category|
                  %li
                    = category.name
                    - if category == model.default_category
```

Debugging notes:

```
p.default_category_id
=> "5d2b0b589ca36d001a8c624d"
Workarea::Categorization.new(p).default_model
=> nil
Workarea::Categorization.new(p).manual_default_model
=> nil
c=Workarea::Catalog::Category.find(p.default_category_id)
=> #<Workarea::Catalog::Category _id: 5d2b0b589ca36d001a8c624d ... >
c.active?
=> false
```

**Comment by tubbo** [comment]
this got fixed a while back
