### ISSUE TITLE
Direct Uploads Fail Locally

### ISSUE THREAD

**Issue by tubbo** [workarea-commerce/workarea#19]
**Describe the bug**
When directly uploading assets, either on `/admin/content_assets` or in a content block itself, and the S3 bucket is configured properly, assets can still fail to upload if the `Workarea.config.host` does not match 

**To Reproduce**
1. Configure your app with S3 secrets and a `config.host` like `example.com`. 
2. Go to `/admin/content_assets` and try to upload an asset
3. You'll get a "Something Went Wrong" message, and CORS warnings in the JS console

**Expected behavior**
The asset should upload successfully.

**Workarea Setup (please complete the following information):**
- Workarea v3.4.14

**Comment by tubbo** [comment]
this one is ready for QA

**Comment by meowsus** [comment]
![](https://github.trello.services/images/mini-trello-icon.png) [Direct Uploads Fail Locally](https://trello.com/c/jjQp5hT3/3-direct-uploads-fail-locally)

**Comment by jyucis** [comment]
test
