### ISSUE TITLE
Bundle warnings cause task to fail

### ISSUE THREAD

**Issue by lanceharman** [workarea-commerce/workarea#191]
rails workarea:services:up can fail do to warnings printed by the bundle show command used to `File.join()` in workarea/core/lib/tasks/services.rake

I solved this by running `bundle config --local disable_platform_warnings true` but I imagine there are other warnings that can also throw off the services:up task.

Either the method should be updated or the documentation should mention issues/solutions around this.

Ref Step 4 of https://developer.workarea.com/articles/create-a-new-app.html

**Comment by bencrouse** [comment]
Thanks for reporting @lanceharman, I opened a PR to fix the issue: https://github.com/workarea-commerce/workarea/pull/192
