### ISSUE TITLE
Feedback for "Infrastructure" doc

### ISSUE THREAD

**Issue by gajendrajena** [workarea-commerce/workarea#298]
Feedback for "Infrastructure" (/articles/infrastructure.html):
The following section refers to a github repository

https://developer.workarea.com/articles/infrastructure.html#web

https://github.com/workarea-commerce/workarea-commerce-cloud
which seems to be moved out of github.
Should be update with the new url.

**Comment by mcfearsome** [comment]
Hi @gajendrajena, workarea-commerce-cloud is a private repo and only available for install for Workarea Commerce Cloud subscribers

**Comment by chriscressman** [comment]
Thanks for reporting this @gajendrajena. Since the linked repository is private to the Workarea Commerce organization, it doesn't make sense to include it in the docs. I opened https://github.com/workarea-commerce/workarea/pull/300 to remove the link.
