### ISSUE TITLE
Editing Content Blocks drops all custom class tags

### ISSUE THREAD

**Issue by jcall-rmo** [workarea-commerce/workarea#315]
When we are creating pages, we use custom <div class=""> tags so that we can style it how we like. However, once we edit anything else on that content block after it was saved, it appears to drop our custom class tag and all styling associated with it.

Below is a short GIF showing the issue

![class disappearing2](https://user-images.githubusercontent.com/59977014/72556740-7f2ca380-385c-11ea-8487-05c2d1aea3f5.gif)

To replicate:

1. create any sort of text in a content block and, using the HTML editor, assign it a custom class tag
2. assign the custom tag some CSS styling using the advanced tab
3. go back into the content block and edit anything else, such as the display for certain devices. You should notice the CSS styling fall off and if you check the HTML on your text, it is gone.

**Comment by bencrouse** [comment]
Hi @jcall-rmo ,  I'm not super familiar with this particular part of the system, but I have two ideas for you:

1) I believe this is controlled in this WYSIWYG config: https://github.com/workarea-commerce/workarea/blob/master/admin/app/assets/javascripts/workarea/admin/config.js.erb#L51
You could probably adjust this config based on https://github.com/Voog/wysihtml/wiki/Configuration to get a configuration you like.

2) You could use the HTML content block instead, which will allow you to specify any HTML.

@meowsus may have thoughts, he is more familiar with this than me.

**Comment by GesJeremie** [comment]
@jcall-rmo To add to what @bencrouse said:

In the WYSIWYG config you should be able to tweak the whitelist to accept any classes:

```javascript
// Proper Whitelist
'classes': {
    'wysiwyg-clear-both': 1,
    'wysiwyg-clear-left': 1,
    'wysiwyg-clear-right': 1,
    'wysiwyg-color-aqua': 1,
    'wysiwyg-color-black': 1,
    'wysiwyg-color-blue': 1,
    'wysiwyg-color-fuchsia': 1,
    'wysiwyg-color-gray': 1,
    'wysiwyg-color-green': 1,
    'wysiwyg-color-lime': 1,
    'wysiwyg-color-maroon': 1,
    'wysiwyg-color-navy': 1,
    'wysiwyg-color-olive': 1,
    'wysiwyg-color-purple': 1,
    'wysiwyg-color-red': 1,
    'wysiwyg-color-silver': 1,
    'wysiwyg-color-teal': 1,
    'wysiwyg-color-white': 1,
    'wysiwyg-color-yellow': 1,
    'wysiwyg-float-left': 1,
    'wysiwyg-float-right': 1,
    'wysiwyg-font-size-large': 1,
    'wysiwyg-font-size-larger': 1,
    'wysiwyg-font-size-medium': 1,
    'wysiwyg-font-size-small': 1,
    'wysiwyg-font-size-smaller': 1,
    'wysiwyg-font-size-x-large': 1,
    'wysiwyg-font-size-x-small': 1,
    'wysiwyg-font-size-xx-large': 1,
    'wysiwyg-font-size-xx-small': 1,
    'wysiwyg-text-align-center': 1,
    'wysiwyg-text-align-justify': 1,
    'wysiwyg-text-align-left': 1,
    'wysiwyg-text-align-right': 1
}
```

```javascript
// Whitelist all the things!
'classes': 'any'
```

However, by experience I would suggest to keep the current whitelist and add the few custom classes you need -- While still keeping the pattern `wysiwyg-{name-custom-class}`.

That way you avoid some headaches such as: 

> Oh wait a minute, is .my-awesome-class used in a WYSIWYG in production? Is it safe to remove it?

**Comment by jcall-rmo** [comment]
Perfect! Thanks so much for the help!

**Comment by bencrouse** [comment]
Thanks @GesJeremie !
