### ISSUE TITLE
Unhandled exception in admin when viewing a product

### ISSUE THREAD

**Issue by ryaan-anthony** [workarea-commerce/workarea#33]
Workarea 3.4.11

* Product matches a category product_rule
* Category is not active.
* Admin views product and the "Categories" card attempts to reference an inactive category. 

Error: ```ActionView::Template::Error: undefined method `id' for nil:NilClass```

This test demonstrates the error:

```
require 'test_helper'

module Workarea
  module Admin
    class ProductCardsIntegrationTest < Workarea::IntegrationTest
      include Admin::IntegrationTest

      setup do
        rule = {
          name: 'price',
          operator: 'less_than',
          value: '10'
        }
        create_category(product_rules: [rule], active: false)
        @product = create_product
      end

      def test_view_product_cards
        get admin.catalog_product_path(@product)
      end
    end
  end
end
```

**Comment by meowsus** [comment]
![](https://github.trello.services/images/mini-trello-icon.png) [Unhandled exception in admin when viewing a product](https://trello.com/c/DfGm8R2D/2-unhandled-exception-in-admin-when-viewing-a-product)
