### ISSUE TITLE
Feedback for "Create a New Workarea App" doc

### ISSUE THREAD

**Issue by albertfougy** [workarea-commerce/workarea#337]
In the docs for **Create a New Workarea App** https://developer.workarea.com/articles/create-a-new-app.html#create-a-rails-5-2-application

There is a mistake in the order of operations within the text vs the embedded video. I spent a few hours figuring out the errors before I looked at the video and noticed the mistake.

Instead of this order:
![Screen Shot 2020-01-27 at 2 11 31 AM](https://user-images.githubusercontent.com/17938053/73156180-eb07db00-40aa-11ea-9594-df2661eab316.png)

It should be switched to this:

![WorkArea_screenshot_problem](https://user-images.githubusercontent.com/17938053/73156212-1985b600-40ab-11ea-9ab2-4afc023dfa99.png)

**Comment by bencrouse** [comment]
Thanks @albertfougy, we've fixed this.
