### ISSUE TITLE
decorate test/system/workarea/storefront/pricing_overrides_system_test

### ISSUE THREAD

**Issue by roseliux** [workarea-commerce/workarea#400]
when trying to decorate this test the namespace was declaring my class name 
`Workarea::Storefront::PricingOverridesSystemTest`
but should be under `Workarea::Admin::PricingOverridesSystemTest`
I realize about this because my storefront build start failing and after debugging the original test the class under `Workarea::Admin`

**Comment by bencrouse** [comment]
I don't follow, could you clarify what the bug is? 

The test has the correct module/path, you can see here: https://github.com/workarea-commerce/workarea/blob/v3.5-stable/storefront/test/system/workarea/storefront/pricing_overrides_system_test.rb#L4-L5

**Comment by roseliux** [comment]
Yes sorry @bencrouse  my bad I mistake the files with version 
workarea-storefront-3.4.26/test/system/workarea/storefront/pricing_overrides_system_test.rb
the namespace there is a Workarea:Admin:PricingOverridesSystemTest

after update this was fixed, we can close this.

**Comment by bencrouse** [comment]
Awesome, thanks for looping back @roseliux
