### ISSUE TITLE
Fix combining category and not in category product rules

### ISSUE THREAD

**Issue by bencrouse** [workarea-commerce/workarea#52]
**Describe the bug**
When you create product rules with a category rule for multiple categories and another rule to exclude a category, it doesn't return the correct products.

**To Reproduce**
See attached test

**Expected behavior**
See attached test

**Workarea Setup (please complete the following information):**
 - Workarea Version: `master`

**Comment by ebigler** [comment]
**ISSUE:**
- before this fix self-referential category rules can be created in the admin, but now it shouldn’t be possible to create those anymore

**TEST:**
- create a new category product rule
- try to search for the current category ID
- EXPECTED RESULT: you shouldn’t find any matches

**TEST RESULT:**
- Waiting for the PR to be approved and merged
