### ISSUE TITLE
Feedback for "Prerequisites & Dependencies" page

### ISSUE THREAD

**Issue by SlickJacket** [workarea-commerce/workarea#535]
'applications' is misspelled in the "MongoDB & Mongoid" section of this page.

Excerpt:

"While there is a low level Ruby driver for MongoDB, Workarea uses Mongoid, an Object-Document Mapper, or ODM. Mongoid provides an API that is purposefully similar to Active Record, the library used to persist models in Rails ***applictions*** using relational databases. If you have any familiarity with Active Record, that knowledge should transfer directly to Mongoid."

**Comment by bencrouse** [comment]
This has been fixed, thanks for reporting.
