### ISSUE TITLE
Why are active_segment_ids localized in the Segmentable concern?

### ISSUE THREAD

**Issue by mmannino** [workarea-commerce/workarea#558]
**Is your feature request related to a problem? Please describe.**
No.

**Describe the solution you'd like**
Do not make the id array localized.

**Describe alternatives you've considered**
Dying my hair orange.

**Additional context**
Not a big deal, just weird.  Felt I saw another non-text Mongoid field being localized too, may want to do a quick audit across all models.

**Comment by bencrouse** [comment]
We wanted to allow something being active for a segment to be configurable per-locale for additional flexibility.
