### ISSUE TITLE
Improve display of referrer URLs on Orders Show view

### ISSUE THREAD

**Issue by meowsus** [workarea-commerce/workarea#60]
**Is your feature request related to a problem? Please describe.**
Long referrer URLs look terrible in the table on the Orders Show view.

**Describe the solution you'd like**
Plop these URLs in a text box. Add a copy icon/link.

**Additional context**
Screenshot:
![Crazy-Long-Referrer-URL](https://user-images.githubusercontent.com/1037252/64875816-aa7b5980-d602-11e9-9e55-e7a71ea0a131.png)

**Comment by ebigler** [comment]
PR #81 'works' but there is a remaining issue with the "Failed to Copy" button being displayed

Here is a screen recording showing the error, but then followed by successfully copying the URL:
![QA_workarea-60](https://user-images.githubusercontent.com/50744988/65801494-38009280-e147-11e9-9f71-26c99adc2fce.gif)

Also, here's a screenshot of the 'failed to copy' button placement:
![copy_Referrer-URL.png](https://images.zenhubusercontent.com/5d85284bfcb2fd0001b7270a/e537e512-b103-41cc-b593-6b6eb4782b4a)
