### ISSUE TITLE
Install on Digital Ocean

### ISSUE THREAD

**Issue by osseonews** [workarea-commerce/workarea#78]
Any documentation on how to install this application on Digital Ocean? The docs for installation are really based on a local installation, not a host. Not really clear how to install this on a third-party server, like at Digital Ocean, other than that we need Docker and Rails installed. Any ideas? Thanks.

**Comment by bencrouse** [comment]
Hi there, for now we have two quick articles to help with this
* Required infrastructure https://developer.workarea.com/articles/infrastructure.html
* ENV var configuration for hosting https://developer.workarea.com/articles/configuration-for-hosting.html

We'll be looking at expanding this soon for different hosting providers. Thanks for taking the time to open this issue and let us know!

**Comment by osseonews** [comment]
Thanks. The docs are quite complex. Any chance you can create a step-by-step process on how to install this at Digital Ocean? Similar to what Discourse (another ROR app) does for it's software, see here: https://github.com/discourse/discourse/blob/master/docs/INSTALL-cloud.md  . Also, would be great if you just had a 1-click install app at Digital Ocean, like how Discourse does it. Then it's a really easy installation. See here: https://marketplace.digitalocean.com/

thanks.

**Comment by bencrouse** [comment]
Yeah, that's pretty nice. We'll take a look. Thanks again.

**Comment by tubbo** [comment]
Hey @osseonews, just an update that we're currently submitting our one-click droplet for DigitalOcean. I'll ping you if/when it gets approved. It's got an interactive setup that starts when you first log in to the machine via SSH, to make the install procedure a bit less complex.

**Comment by osseonews** [comment]
That's great. Looking forward to testing it out.

**Comment by drinkmorewaters** [comment]
This is great for smaller stores. (Even thought that's not your target)

**Comment by tubbo** [comment]
moving this ticket to workarea-commerce/one-click-droplet which is where we'll be accepting any other issues related to the droplet.

**Comment by tubbo** [comment]
This project is being tracked on https://github.com/workarea-commerce/one-click-droplet, so I'm gonna close this. If you have any issues installing, let us know by creating a new issue in that repo.
