### ISSUE TITLE
Remove Schema.org structured data from private pages

### ISSUE THREAD

**Issue by meowsus** [workarea-commerce/workarea#82]
Structured data has no real use on pages that won't be crawled by search engines. Remove it from Account and Checkout pages.

Reported by @sperks38

**Comment by sperks38** [comment]
@meowsus I was going to give this one a spin if you haven't started on it yet!

**Comment by meowsus** [comment]
@sperks38 Whoops! I just saw your commend right after I pushed #107! Sorry to take the wind out of your sails!
